//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 27/02/2016 20:08:39
namespace ServiceODataWeb.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for TallerEntities in the schema.
    /// </summary>
    public partial class TallerEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TallerEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TallerEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "TallerModel", "ServiceODataWeb.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ServiceODataWeb.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("TallerModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Clientes> Clientes
        {
            get
            {
                if ((this._Clientes == null))
                {
                    this._Clientes = base.CreateQuery<Clientes>("Clientes");
                }
                return this._Clientes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Clientes> _Clientes;
        /// <summary>
        /// There are no comments for Vehiculos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Vehiculos> Vehiculos
        {
            get
            {
                if ((this._Vehiculos == null))
                {
                    this._Vehiculos = base.CreateQuery<Vehiculos>("Vehiculos");
                }
                return this._Vehiculos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Vehiculos> _Vehiculos;
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
        /// <summary>
        /// There are no comments for Vehiculos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVehiculos(Vehiculos vehiculos)
        {
            base.AddObject("Vehiculos", vehiculos);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"TallerModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><En" +
                "tityType Name=\"Clientes\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=" +
                "\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"nomb" +
                "re\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicod" +
                "e=\"true\" /><Property Name=\"apellidos\" Type=\"Edm.String\" Nullable=\"false\" MaxLeng" +
                "th=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"Vehiculos" +
                "\" Relationship=\"TallerModel.FK_Vehiculos_Clientes\" ToRole=\"Vehiculos\" FromRole=\"" +
                "Clientes\" /></EntityType><EntityType Name=\"Vehiculos\"><Key><PropertyRef Name=\"id" +
                "\" /><PropertyRef Name=\"idcliente\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" N" +
                "ullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.mic" +
                "rosoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"marca\" Type=\"Edm.String" +
                "\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property" +
                " Name=\"modelo\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"fa" +
                "lse\" Unicode=\"true\" /><Property Name=\"idcliente\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"motivo\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"Clientes\" Relation" +
                "ship=\"TallerModel.FK_Vehiculos_Clientes\" ToRole=\"Clientes\" FromRole=\"Vehiculos\" " +
                "/></EntityType><Association Name=\"FK_Vehiculos_Clientes\"><End Type=\"TallerModel." +
                "Clientes\" Role=\"Clientes\" Multiplicity=\"1\" /><End Type=\"TallerModel.Vehiculos\" R" +
                "ole=\"Vehiculos\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Clien" +
                "tes\"><PropertyRef Name=\"id\" /></Principal><Dependent Role=\"Vehiculos\"><PropertyR" +
                "ef Name=\"idcliente\" /></Dependent></ReferentialConstraint></Association></Schema" +
                "><Schema Namespace=\"ServiceOData.Model\" xmlns=\"http://schemas.microsoft.com/ado/" +
                "2009/11/edm\"><EntityContainer Name=\"TallerEntities\" m:IsDefaultEntityContainer=\"" +
                "true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.microsoft.com/ado/20" +
                "09/02/edm/annotation\"><EntitySet Name=\"Clientes\" EntityType=\"TallerModel.Cliente" +
                "s\" /><EntitySet Name=\"Vehiculos\" EntityType=\"TallerModel.Vehiculos\" /><Associati" +
                "onSet Name=\"FK_Vehiculos_Clientes\" Association=\"TallerModel.FK_Vehiculos_Cliente" +
                "s\"><End Role=\"Clientes\" EntitySet=\"Clientes\" /><End Role=\"Vehiculos\" EntitySet=\"" +
                "Vehiculos\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></e" +
                "dmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for TallerModel.Clientes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Clientes
    {
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="nombre">Initial value of nombre.</param>
        /// <param name="apellidos">Initial value of apellidos.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Clientes CreateClientes(int ID, string nombre, string apellidos)
        {
            Clientes clientes = new Clientes();
            clientes.id = ID;
            clientes.nombre = nombre;
            clientes.apellidos = apellidos;
            return clientes;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                this._nombre = value;
                this.OnnombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nombre;
        partial void OnnombreChanging(string value);
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for Property apellidos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string apellidos
        {
            get
            {
                return this._apellidos;
            }
            set
            {
                this.OnapellidosChanging(value);
                this._apellidos = value;
                this.OnapellidosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _apellidos;
        partial void OnapellidosChanging(string value);
        partial void OnapellidosChanged();
        /// <summary>
        /// There are no comments for Vehiculos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Vehiculos> Vehiculos
        {
            get
            {
                return this._Vehiculos;
            }
            set
            {
                if ((value != null))
                {
                    this._Vehiculos = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Vehiculos> _Vehiculos = new global::System.Collections.ObjectModel.Collection<Vehiculos>();
    }
    /// <summary>
    /// There are no comments for TallerModel.Vehiculos in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// idcliente
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id", "idcliente")]
    public partial class Vehiculos
    {
        /// <summary>
        /// Create a new Vehiculos object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="marca">Initial value of marca.</param>
        /// <param name="modelo">Initial value of modelo.</param>
        /// <param name="idcliente">Initial value of idcliente.</param>
        /// <param name="motivo">Initial value of motivo.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Vehiculos CreateVehiculos(int ID, string marca, string modelo, int idcliente, string motivo)
        {
            Vehiculos vehiculos = new Vehiculos();
            vehiculos.id = ID;
            vehiculos.marca = marca;
            vehiculos.modelo = modelo;
            vehiculos.idcliente = idcliente;
            vehiculos.motivo = motivo;
            return vehiculos;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property marca in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string marca
        {
            get
            {
                return this._marca;
            }
            set
            {
                this.OnmarcaChanging(value);
                this._marca = value;
                this.OnmarcaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _marca;
        partial void OnmarcaChanging(string value);
        partial void OnmarcaChanged();
        /// <summary>
        /// There are no comments for Property modelo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string modelo
        {
            get
            {
                return this._modelo;
            }
            set
            {
                this.OnmodeloChanging(value);
                this._modelo = value;
                this.OnmodeloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _modelo;
        partial void OnmodeloChanging(string value);
        partial void OnmodeloChanged();
        /// <summary>
        /// There are no comments for Property idcliente in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int idcliente
        {
            get
            {
                return this._idcliente;
            }
            set
            {
                this.OnidclienteChanging(value);
                this._idcliente = value;
                this.OnidclienteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _idcliente;
        partial void OnidclienteChanging(int value);
        partial void OnidclienteChanged();
        /// <summary>
        /// There are no comments for Property motivo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string motivo
        {
            get
            {
                return this._motivo;
            }
            set
            {
                this.OnmotivoChanging(value);
                this._motivo = value;
                this.OnmotivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _motivo;
        partial void OnmotivoChanging(string value);
        partial void OnmotivoChanged();
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Clientes Clientes
        {
            get
            {
                return this._Clientes;
            }
            set
            {
                this._Clientes = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Clientes _Clientes;
    }
}
